### ISSUE TITLE
Issue with postinstall script on Windows and problems building locale packages

### ISSUE THREAD

**Issue by emyhrer** [js-joda/js-joda-locale#41] opened 2017-12-06 02:23 UTC
Hello,

Thanks for providing this plugin to js-joda.

I am looking to use js-joda-locale using prebuilt packages like described in the Readme and have run into one small issue on Windows I wanted to let you know about, and one issue I was hoping you could provide some pointers to overcome.

1. The `postinstall`, `build-dist` and `test-coverage` scripts fail in my Windows environment because of the way environment variables are set in versions 0.8.2 and 1.0.0.  This can be solved by using `cross-env` when defining the scripts in package.json. 

2. I am not yet able to get js-joda-locale and cldr-data to play nice together. 

    When using the prebuilt packages approach as described in the Readme I am able to generate the packages, but they all end up the same size at ~44MB regardless of which locales I configure. I suspect this is because of the same issues I see when using the webpack approach to minimizing the size and that the whole thing always end up getting packaged. Functionally these packages work as expected, but the size is obviously going to be an issue.

    When using the webpack approach I run into a series of issues during the build_package.js script. I can get around the missing `fs` module by targeting `node `as opposed to `web`, after which the next error complains about a return statement outside of a function in the cldr-data package. After manually changing this in cldr-data to see if I could build my packages, other issues keep popping up. The next issue is the following error: 

    > ../cldr-data/install.js\n46:13-40 Critical dependency: the request of a dependency is an expression

    I would like to stay away from making changes to the `cldr-data` package to resolve these issues if possible.

Here are the pertinent parts of my package.json:
```json
"cldr-data": "32.0.0",
"cldrjs": "0.5.0",
"js-joda": "1.6.2",
"js-joda-locale": "^1.0.0",
"js-joda-timezone": "1.1.5",
"webpack": "^3.10.0",
```

```json
"cldr-data-coverage": "core",
"cldr-data-urls-filter": "(cldr-core|cldr-numbers-modern|cldr-dates-modern)",
"js-joda-locale": {
  "packages": {
    "en": [
      "en"
    ]
  },
  "stats": false,
  "debug": false
}
```
and webpack.config.js:

```json
resolve:
{
  // either setting cldr-data alias
  alias:
  {
    'cldr-data$': path.resolve(__dirname, 'node_modules/js-joda-locale/utils/load_cldrData.js')
  }
},
// or setting target to node
target: "node",
// and using the CldrDataIgnorePlugin
plugins:
[
  new CldrDataIgnorePlugin("<absolute path>node_modules", ['en'])
] 
```
I suspect there is something in my setup that is different than what is expected, and would appreciate any pointers to narrow this down.

Thanks and regards,

Einar

**Comment by phueper** [comment] 2017-12-06 18:01
Hi @emyhrer 

thanks for using js-joda-locale and thanks for reporting this

i have to admit, that i never tried building it on windows.

I will try to set this up and reproduce it in a Windows Machine, 44MB is definitely not where we want to be with package size

Regards, Pattrick

**Comment by phueper** [comment] 2017-12-17 18:16
Sorry, I didn't have time yet to look into this further.. I hope to have some time during Christmas break

**Comment by thiagodp** [comment] 2018-04-20 16:54
Hi, it's happening the same here.

```bash
> js-joda-locale@1.0.0 postinstall C:\code\tmp\js-joda-test\node_modules\js-joda-locale
> POSTINSTALL_BUILD=1 postinstall-build __always_build__ --only-as-dependency --script build_package

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-joda-locale@1.0.0 postinstall: `POSTINSTALL_BUILD=1 postinstall-build __always_build__ --only-as-dependency --script build_package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-joda-locale@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The problem appears to be in `postinstall` script. Probably it was not tested before in Windows. I would like to suggest to fix it or disable it temporarily. Since the error occurs, *npm* rollbacks downloaded files and it is not possible to build it.

**Comment by phueper** [comment] 2018-05-13 15:16
we'll provide packages with prebuilt locales soon, the postinstall will be removed then

**Comment by phueper** [comment] 2018-11-01 16:42
it's been a long time ... the postinstall is no longer needed, locale specific packages have been released ... i'll close this issue

**Closed by phueper** 2018-11-01 16:42 UTC

**Comment by emyhrer** [comment] 2018-11-02 17:58
Just confirming that this now works well for us on Windows with the locale specific packages. Thanks very much for resolving!
