### ISSUE TITLE
Problem when using js-joda-locale from Typescript / Angular

### ISSUE THREAD

**Issue by SimonLuckenuik** [js-joda/js-joda-locale#34] opened 2017-10-27 12:53 UTC
Hi!

I am trying to use js-joda-locale from an Angular based project and running into issues.
See attached repro project: [jsjodalocale.zip](https://github.com/js-joda/js-joda-locale/files/1422088/jsjodalocale.zip)

App was created with Angular CLI, steps below:
1) _ng new jsjodalocale_
2) _ng eject_ to have the proper webpackconfig.js generated
3) Modify view and component (see below)
4) Modify webpack.config.js to add null-loader rule to minimize cldr-data size (see below)
5) Modify package.json to add (see below) _"cldr-data-coverage": "core"_,  _"cldr-data-urls-filter": "(cldr-core|cldr-numbers-modern|cldr-dates-modern)",_  along with following dependencies.
    "js-joda": "1.6.2",
    "js-joda-locale": "0.1.0",
    "js-joda-timezone": "1.1.5",
    "cldr-data": "31.0.2",
    "cldrjs": "0.5.0",
6) _npm run start_, builds correctly
7) Navigate to http://localhost:4200/ error appears in console.

Error:
```
AppComponent.html:1 ERROR TypeError: (0 , _cldrData2.default) is not a function
    at new CldrDateTimeTextProvider (js-joda-locale.js:641)
    at DateTimeFormatterBuilder.appendTextFieldStyle (js-joda-locale.js:421)
    at DateTimeFormatterBuilder.appendText (js-joda-locale.js:404)
    at DateTimeFormatterBuilder._parseField (js-joda.js:5086)
    at DateTimeFormatterBuilder._parsePattern (js-joda.js:4893)
    at DateTimeFormatterBuilder.appendPattern (js-joda.js:4819)
    at Function.ofPattern (js-joda.js:2194)
    at AppComponent.get [as title] (app.component.ts:22)
    at Object.eval [as updateRenderer] (AppComponent.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js:13105)
```
Line from js-joda-locale that raises the error: `_cldrjs2.default.load((0, _cldrData2.default)('supplemental/likelySubtags'));`

app.component.html:
```
<h1>
Time: {{title}}!
</h1>
```

app.component.ts:
```
import { Component } from '@angular/core';
declare var require: any;
var _jsJoda = require('js-joda');
var _jsJodaTimezone = require('js-joda-timezone');
var _jsJodaLocale = require('js-joda-locale');
_jsJoda.use(_jsJodaTimezone).use(_jsJodaLocale);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  get title(): string  {
        let dateFormat = "hh:mm a";
        let newValue = _jsJoda.LocalTime.of(23, 13, 3);
        let formatter = _jsJoda.DateTimeFormatter.ofPattern(dateFormat).withLocale(_jsJoda.Locale.ENGLISH);
        let value = newValue.format(formatter);
        return value;
  }
}
```

package.json:
```
{
  "name": "jsjodalocale",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "webpack-dev-server --port=4200",
    "build": "webpack",
    "test": "karma start ./karma.conf.js",
    "lint": "ng lint",
    "e2e": "protractor ./protractor.conf.js",
    "pree2e": "webdriver-manager update --standalone false --gecko false --quiet"
  },
  "private": true,
  "cldr-data-coverage": "core",
  "cldr-data-urls-filter": "(cldr-core|cldr-numbers-modern|cldr-dates-modern)",
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "cldr-data": "31.0.2",
    "cldrjs": "0.5.0",
    "core-js": "^2.4.1",
    "js-joda": "1.6.2",
    "js-joda-locale": "0.1.0",
    "js-joda-timezone": "1.1.5",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3",
    "webpack-dev-server": "~2.7.1",
    "webpack": "~3.7.1",
    "autoprefixer": "^6.5.3",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^1.1.5",
    "null-loader": "0.1.1",
    "html-webpack-plugin": "^2.29.0",
    "less-loader": "^4.0.5",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.6.2",
    "circular-dependency-plugin": "^3.0.0",
    "webpack-concat-plugin": "1.4.0",
    "copy-webpack-plugin": "^4.1.1"
  }
}
```

webpack rule added in webpack.config.js:
```
      {
        "test": path.join(process.cwd(), "node_modules\\cldr-data\\"),
        "loader": "null-loader",
        "exclude": [
          path.join(process.cwd(), "node_modules\\cldr-data\\main\\en\\"),
          path.join(process.cwd(), "node_modules\\cldr-data\\supplemental\\")
        ],
      },
```
Thanks!
Simon

**Comment by phueper** [comment] 2017-10-27 13:00
Hi,

thanks for reporting and thanks for using js-joda-locale :) 

i'll have a look

Regards, Pattrick

**Comment by phueper** [comment] 2017-10-27 13:19
Hi,

the provided zip doesn't build for me... i unpacked it, ran `npm install` and `npm run build` or `npm run start` ... i'm not much of an angular user, i'm a bit lost here... error message:

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module' in '/home/phueper/work/js-joda-locale/tmp/angular_test_issues/src\'
 @ ./src/main.ts 3:0-45
 @ multi ./src/main.ts
```
and
```
ERROR in Entry module not found: Error: Can't resolve '/home/phueper/work/js-joda-locale/tmp/angular_test_issues/src\index.html' in '/home/phueper/work/js-joda-locale/tmp/angular_test_issues'
```

among others...

I suspect, the problem is the `\` at the end of the path, but i don't understand where that comes from ... i'm running on linux, und `\` is not a valid path separator

**Comment by SimonLuckenuik** [comment] 2017-10-27 13:31
Thanks for the quick feedback! I'm running from Windows, maybe that's why. I updated the webpack.config to use / instead of \\ at some locations. Give it a try:
[webpack.config.js.zip](https://github.com/js-joda/js-joda-locale/files/1422187/webpack.config.js.zip)

**Comment by phueper** [comment] 2017-10-27 14:16
Thanks, yes... now the build runs and i can produce the error.

i'll try to look into this over the weekend

Regards, Pattrick

**Comment by phueper** [comment] 2017-10-29 11:19
Hi @SimonLuckenuik 

Once again, thanks for trying out js-joda-locale.

I *did* manage to get this to work in your setup, but i am not really happy with the process as it is right now... i have been thinking of providing js-joda-locale packages *including* the cldr-data for certain locales and i think we need to move into this direction more, because the process of setting up a working environment including cldr-data and js-joda-locale is obviously pretty complicated ... 

Back to your problem... i did forget to put the following info into the documentation... but i also improved the js-joda-locale package a little to include a "workaround cldrData" loader ... I will release this in the next version, but i'm not quite ready to do so, so you will need to use the the current state of the package from my github repo :) 

So... here are the changes i needed to do to your app:

```
diff --git a/package.json b/package.json
index fa26c32..0a84502 100644
--- a/package.json
+++ b/package.json
@@ -28,7 +28,7 @@
     "cldrjs": "0.5.0",
     "core-js": "^2.4.1",
     "js-joda": "1.6.2",
-    "js-joda-locale": "0.1.0",
+    "js-joda-locale": "git+https://github.com/phueper/js-joda-locale.git",
     "js-joda-timezone": "1.1.5",
     "rxjs": "^5.4.2",
     "zone.js": "^0.8.14"
diff --git a/webpack.config.js b/webpack.config.js
index 70f79c0..d85cdd9 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -71,7 +71,7 @@ module.exports = {
     ],
     "symlinks": true,
     "alias": {
-
+      "cldr-data$": path.join(process.cwd(), "node_modules/js-joda-locale/utils/load_cldrData.js"),
     }
   },
   "resolveLoader": {
@@ -111,7 +111,8 @@ module.exports = {
         "loader": "null-loader",
         "exclude": [
           path.join(process.cwd(), "node_modules/cldr-data/main/en/"),
-          path.join(process.cwd(), "node_modules/cldr-data/supplemental/")
+          path.join(process.cwd(), "node_modules/cldr-data/supplemental/"),
+          path.join(process.cwd(), "node_modules/cldr-data/availableLocales.json")
         ],
       },
       {
```

The changes are: 

- use the github repo instead of the released package of js-joda-locale. This includes a `utils/load_cldrData.js` file
- alias this file as the `cldr-data` package... since the npm `cldr-data\index.js` file uses modules only available in node but not in the browser, this is necessary
- add the availableLocales file to the null-loader exclusion... this might actually not be strictly necessary for you :) 

For me this solves the error and shows a formatted time on the app in the browser.

Again, since i think this step is pretty cumbersome i'm thinking about ways to provide a package including the locale data that would make these steps unncessary... but for now, i would be happy if you can test this and verify that it is working for you

Thanks, Regards, Pattrick

**Comment by phueper** [comment] 2017-11-05 21:15
We just release v0.8.0 ... this now includes the possibility to build locale specific packages as a `postinstall` step of js-joda-locale ... see README ... it also seems to work with your sample project. I will thus close this issue now @SimonLuckenuik  ... please feel free to reopen, if you continue to have problems using `js-joda-locale`.

I really appreciate any feedback since we are getting pretty close to releasing a 1.0 version of `js-joda-locale` i think.

Regards, Pattrick

**Closed by phueper** 2017-11-05 21:15 UTC

**Comment by SimonLuckenuik** [comment] 2017-11-05 22:59
Thank you for the update Pattrick and quick support, I will give it  try hopefully this week or next week when we will integrate the js-joda parser into our app.

**Comment by phueper** [comment] 2017-11-05 23:10
👍 feel free to contact me if you have any issues or questions. (or, even better, if you don't ;-)) 
I'm really interested to get feedback from users. To understand how js-joda-locale is used and how it could be improved

Regards, Pattrick
